######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 15 14:26:57 2013
######################################################################

TEMPLATE = app

include($(SOURCE_HOME)/preset.pri)
include($(SOURCE_HOME)/postset.pri)
#include($(SOURCE_HOME)/test.pri)

INCLUDEPATH += $$SOURCE/scada/include-scada

LIBS += -lnetapi -ltaos
SOURCES += src/main.cpp
           
           
          
